tcms/bugs/urls.py
# Copyright (c) 2019-2020 Alexander Todorov <atodorov@MrSenko.com>

# Licensed under the GPL 2.0: https://www.gnu.org/licenses/old-licenses/gpl-2.0.html

from django.urls import re_path

from . import views

urlpatterns = [
    re_path(r'^(?P<pk>\d+)/$', views.Get.as_view(), name='bugs-get'),
    re_path(r'^new/$', views.New.as_view(), name='bugs-new'),
    re_path(r'^(?P<pk>\d+)/edit/$', views.Edit.as_view(), name='bugs-edit'),
    re_path(r'^search/$', views.Search.as_view(), name='bugs-search'),
    re_path(r'^comment/$', views.AddComment.as_view(), name='bugs-comment'),
]

tcms/kiwi_auth/urls.py
# -*- coding: utf-8 -*-

from django.urls import re_path
from django.contrib.auth import views as contrib_auth_views
from django.urls import reverse_lazy

from tcms.kiwi_auth import views

urlpatterns = [
    re_path(r'^(?P<username>[\w.@+-]+)/profile/$', views.Profile.as_view(),
            name='tcms-profile'),

    re_path(r'^register/$', views.Register.as_view(), name='tcms-register'),
    re_path(r'^confirm/(?P<activation_key>[A-Za-z0-9\-]+)/$', views.Confirm.as_view(),
            name='tcms-confirm'),

    re_path(r'^login/$', views.LoginViewWithCustomTemplate.as_view(), name='tcms-login'),
    re_path(r'^logout/$',
            contrib_auth_views.LogoutView.as_view(next_page=reverse_lazy('tcms-login')),
            name='tcms-logout'),


    re_path(r'^passwordreset/$', views.PasswordResetView.as_view(),
            name='tcms-password_reset'),
    re_path(r'^passwordreset/done/$', contrib_auth_views.PasswordResetDoneView.as_view(),
            name='password_reset_done'),
    re_path(r'^passwordreset/confirm/(?P<uidb64>[0-9A-Za-z]+)-(?P<token>.+)/$',
            contrib_auth_views.PasswordResetConfirmView.as_view(), name='password_reset_confirm'),
    re_path(r'^passwordreset/complete/$',
            contrib_auth_views.PasswordResetCompleteView.as_view(), name='password_reset_complete'),
]

tcms/testruns/urls.py
from django.urls import re_path

from . import views

urlpatterns = [
    re_path(r'^new/$', views.CreateTestRunView.as_view(), name='testruns-new'),
    re_path(r'^(?P<pk>\d+)/$', views.GetTestRunView.as_view(), name='testruns-get'),
    re_path(r'^(?P<pk>\d+)/clone/$', views.CloneTestRunView.as_view(), name='testruns-clone'),
    re_path(r'^(?P<pk>\d+)/edit/$', views.EditTestRunView.as_view(), name='testruns-edit'),

    re_path(r'^(?P<pk>\d+)/report/$', views.TestRunReportView.as_view(),
            name='run-report'),

    re_path(r'^(?P<pk>\d+)/changestatus/$', views.ChangeTestRunStatusView.as_view(),
            name='testruns-change_status'),

    re_path(r'^(?P<pk>\d+)/assigncase/$', views.AddCasesToRunView.as_view(),
            name='add-cases-to-run'),

    re_path(r'^(?P<pk>\d+)/cc/$', views.ManageTestRunCC.as_view(), name='testruns-cc'),
    re_path(r'^search/$', views.SearchTestRunView.as_view(), name='testruns-search'),
]

tcms/urls.py
# -*- coding: utf-8 -*-
from importlib import import_module

import pkg_resources
from attachments import urls as attachments_urls
from django.conf import settings
from django.urls import re_path
from django.conf.urls import include
from django.conf.urls.static import static
from django.contrib import admin
from django.views.generic import TemplateView
from django.views.i18n import JavaScriptCatalog
from grappelli import urls as grappelli_urls
from modernrpc.core import JSONRPC_PROTOCOL, XMLRPC_PROTOCOL
from modernrpc.views import RPCEntryPoint

from tcms.core import ajax
from tcms.core import views as core_views
from tcms.kiwi_auth import urls as auth_urls
from tcms.telemetry import urls as telemetry_urls
from tcms.testcases import urls as testcases_urls
from tcms.testplans import urls as testplans_urls
from tcms.testruns import urls as testruns_urls

urlpatterns = [
    re_path(r'^$', core_views.DashboardView.as_view(), name='core-views-index'),
    re_path(r'^xml-rpc/', RPCEntryPoint.as_view(protocol=XMLRPC_PROTOCOL)),
    re_path(r'^json-rpc/$', RPCEntryPoint.as_view(protocol=JSONRPC_PROTOCOL)),
    re_path(r'^navigation/', core_views.NavigationView.as_view(), name='iframe-navigation'),
    re_path(r'^translation-mode/', core_views.TranslationMode.as_view(), name='translation-mode'),

    re_path(r'^grappelli/', include(grappelli_urls)),
    re_path(r'^admin/', admin.site.urls),

    re_path(r'^attachments/', include(attachments_urls, namespace='attachments')),

    # Ajax call responder
    re_path(r'^ajax/update/cases-actor/$', ajax.UpdateTestCaseActorsView.as_view(),
            name='ajax.update.cases-actor'),
    re_path(r'^management/tags/$', ajax.tags, name='ajax-tags'),

    # Account information zone, such as login method
    re_path(r'^accounts/', include(auth_urls)),

    # Testplans zone
    re_path(r'^plan/', include(testplans_urls.plan_urls)),
    re_path(r'^plans/', include(testplans_urls.plans_urls)),

    # Testcases zone
    re_path(r'^case/', include(testcases_urls.case_urls)),
    re_path(r'^cases/', include(testcases_urls.cases_urls)),

    # Testruns zone
    re_path(r'^runs/', include(testruns_urls)),

    re_path(r'^telemetry/', include(telemetry_urls)),

    # JavaScript translations, see
    # https://docs.djangoproject.com/en/2.1/topics/i18n/translation/#django.views.i18n.JavaScriptCatalog
    re_path(r'^jsi18n/$', JavaScriptCatalog.as_view(), name='javascript-catalog'),
]


# conditional import b/c this App can be disabled
if 'tcms.bugs.apps.AppConfig' in settings.INSTALLED_APPS:
    from tcms.bugs import urls as bugs_urls
    urlpatterns.append(re_path(r'^bugs/', include(bugs_urls)))


for plugin in pkg_resources.iter_entry_points('kiwitcms.plugins'):
    plugin_urls = import_module('%s.urls' % plugin.module_name)
    urlpatterns.append(
        re_path(r'^%s/' % plugin.name, include(plugin_urls))
    )


if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns.extend([
        re_path(r'^500/$', TemplateView.as_view(template_name="500.html")),
        re_path(r'^404/$', TemplateView.as_view(template_name="404.html")),
    ])

    try:
        import debug_toolbar

        urlpatterns += [
            re_path(r'^__debug__/', include(debug_toolbar.urls)),
        ]
    # in case we're trying to debug in production
    # and debug_toolbar is not installed
    except ImportError:
        pass


# Overwrite default 500 handler
# More details could see django.core.urlresolvers._resolve_special()
handler500 = 'tcms.core.views.server_error'

tcms/testcases/models.py
# -*- coding: utf-8 -*-
import vinaigrette
from django.conf import settings
from django.db import models
from django.db.models import ObjectDoesNotExist
from django.db.models import Q
from django.urls import reverse
from django.utils.translation import override

from tcms.core.history import KiwiHistoricalRecords
from tcms.core.models import TCMSActionModel
from tcms.rpc.serializer import TestCaseRPCSerializer
from tcms.rpc.utils import distinct_filter
from tcms.testcases.fields import MultipleEmailField


class TestCaseStatus(TCMSActionModel):
    name = models.CharField(max_length=255)
    description = models.TextField(null=True, blank=True)

    class Meta:
        verbose_name = "Test case status"
        verbose_name_plural = "Test case statuses"

    def __str__(self):
        return self.name

    @classmethod
    def get_proposed(cls):
        return cls.objects.get(name='PROPOSED')

    @classmethod
    def get_confirmed(cls):
        return cls.objects.get(name='CONFIRMED')

    def is_confirmed(self):
        with override('en'):
            return self.name == 'CONFIRMED'


# register model for DB translations
vinaigrette.register(TestCaseStatus, ['name'])


class Category(TCMSActionModel):
    name = models.CharField(max_length=255)
    product = models.ForeignKey('management.Product', related_name="category",
                                on_delete=models.CASCADE)
    description = models.TextField(blank=True)

    class Meta:
        verbose_name_plural = u'test case categories'
        unique_together = ('product', 'name')

    def __str__(self):
        return self.name


class TestCase(TCMSActionModel):
    history = KiwiHistoricalRecords()

    create_date = models.DateTimeField(auto_now_add=True)
    is_automated = models.BooleanField(default=False)
    script = models.TextField(blank=True, null=True)
    arguments = models.TextField(blank=True, null=True)
    extra_link = models.CharField(max_length=1024, default=None, blank=True, null=True)
    summary = models.CharField(max_length=255, db_index=True)
    requirement = models.CharField(max_length=255, blank=True, null=True)
    notes = models.TextField(blank=True, null=True)
    text = models.TextField(blank=True)

    case_status = models.ForeignKey(TestCaseStatus, on_delete=models.CASCADE)
    category = models.ForeignKey(Category, related_name='category_case',
                                 on_delete=models.CASCADE)
    priority = models.ForeignKey('management.Priority', related_name='priority_case',
                                 on_delete=models.CASCADE)
    author = models.ForeignKey(settings.AUTH_USER_MODEL, related_name='cases_as_author',
                               on_delete=models.CASCADE)
    default_tester = models.ForeignKey(settings.AUTH_USER_MODEL,
                                       related_name='cases_as_default_tester',
                                       blank=True,
                                       null=True,
                                       on_delete=models.CASCADE)
    reviewer = models.ForeignKey(settings.AUTH_USER_MODEL,
                                 related_name='cases_as_reviewer',
                                 null=True,
                                 on_delete=models.CASCADE)

    # FIXME: related_name should be cases instead of case. But now keep it
    # named case due to historical reason.
    plan = models.ManyToManyField('testplans.TestPlan', related_name='case',
                                  through='testcases.TestCasePlan')

    component = models.ManyToManyField('management.Component', related_name='cases',
                                       through='testcases.TestCaseComponent')

    tag = models.ManyToManyField('management.Tag', related_name='case',
                                 through='testcases.TestCaseTag')

    def __str__(self):
        return self.summary

    @classmethod
    def to_xmlrpc(cls, query=None):

        _query = query or {}
        qs = distinct_filter(TestCase, _query).order_by('pk')
        serializer = TestCaseRPCSerializer(model_class=cls, queryset=qs)
        return serializer.serialize_queryset()

    @classmethod
    def list(cls, query, plan=None):
        """List the cases with request"""

        if not plan:
            queryset = cls.objects
        else:
            queryset = cls.objects.filter(plan=plan)

        if query.get('case_id_set'):
            queryset = queryset.filter(pk__in=query['case_id_set'])

        if query.get('search'):
            queryset = queryset.filter(
                Q(pk__icontains=query['search']) |
                Q(summary__icontains=query['search']) |
                Q(author__email__startswith=query['search'])
            )

        if query.get('summary'):
            queryset = queryset.filter(Q(summary__icontains=query['summary']))

        if query.get('author'):
            queryset = queryset.filter(
                Q(author__first_name__startswith=query['author']) |
                Q(author__last_name__startswith=query['author']) |
                Q(author__username__icontains=query['author']) |
                Q(author__email__startswith=query['author'])
            )

        if query.get('default_tester'):
            queryset = queryset.filter(
                Q(default_tester__first_name__startswith=query[
                    'default_tester']) |
                Q(default_tester__last_name__startswith=query[
                    'default_tester']) |
                Q(default_tester__username__icontains=query[
                    'default_tester']) |
                Q(default_tester__email__startswith=query[
                    'default_tester'])
            )

        if query.get('tag__name__in'):
            queryset = queryset.filter(tag__name__in=query['tag__name__in'])

        if query.get('category'):
            queryset = queryset.filter(category__name=query['category'].name)

        if query.get('priority'):
            queryset = queryset.filter(priority__in=query['priority'])

        if query.get('case_status'):
            queryset = queryset.filter(case_status__in=query['case_status'])

        # If plan exists, remove leading and trailing whitespace from it.
        # todo: this is the same as the if condition above !!! - this entire method
        # should be removed in favor of API
        plan_str = query.get('plan', '').strip()
        if plan_str:
            try:
                # Is it an integer?  If so treat as a plan_id:
                plan_id = int(plan_str)
                queryset = queryset.filter(plan__pk=plan_id)
            except ValueError:
                # Not an integer - treat plan_str as a plan name:
                queryset = queryset.filter(plan__name__icontains=plan_str)
        del plan_str

        if query.get('product'):
            queryset = queryset.filter(category__product=query['product'])

        if query.get('component'):
            queryset = queryset.filter(component=query['component'])

        if query.get('is_automated'):
            queryset = queryset.filter(is_automated=query['is_automated'])

        return queryset.distinct()

    def add_component(self, component):
        return TestCaseComponent.objects.get_or_create(case=self, component=component)

    def add_tag(self, tag):
        return TestCaseTag.objects.get_or_create(case=self, tag=tag)

    def get_text_with_version(self, case_text_version=None):
        if case_text_version:
            try:
                return self.history.get(history_id=case_text_version).text
            except ObjectDoesNotExist:
                return self.text

        return self.text

    def remove_component(self, component):
        # note: cannot use self.component.remove(component) on a ManyToManyField
        # which specifies an intermediary model so we use the model manager!
        self.component.through.objects.filter(case=self.pk, component=component.pk).delete()

    def remove_tag(self, tag):
        self.tag.through.objects.filter(case=self.pk, tag=tag.pk).delete()

    def _get_absolute_url(self, request=None):
        return reverse('testcases-get', args=[self.pk, ])

    def get_absolute_url(self):
        return self._get_absolute_url()

    def _get_email_conf(self):
        try:
            return self.email_settings
        except ObjectDoesNotExist:
            return TestCaseEmailSettings.objects.create(case=self)

    emailing = property(_get_email_conf)

    def clone(self, new_author, test_plans):
        new_tc = self.__class__.objects.create(
            is_automated=self.is_automated,
            script=self.script,
            arguments=self.arguments,
            extra_link=self.extra_link,
            summary=self.summary,
            requirement=self.requirement,
            case_status=TestCaseStatus.get_proposed(),
            category=self.category,
            priority=self.priority,
            notes=self.notes,
            text=self.text,
            author=new_author,
            default_tester=self.default_tester,
        )

        # apply tags as well
        for tag in self.tag.all():
            new_tc.add_tag(tag)

        for plan in test_plans:
            plan.add_case(new_tc)

            # clone TC category b/c we may be cloning a 'linked'
            # TC which has a different Product that doesn't have the
            # same categories yet
            try:
                tc_category = plan.product.category.get(name=self.category.name)
            except ObjectDoesNotExist:
                tc_category = plan.product.category.create(
                    name=self.category.name,
                    description=self.category.description,
                )
            new_tc.category = tc_category
            new_tc.save()

            # clone TC components b/c we may be cloning a 'linked'
            # TC which has a different Product that doesn't have the
            # same components yet

tcms/bugs/forms.py
# Copyright (c) 2019 Alexander Todorov <atodorov@MrSenko.com>

# Licensed under the GPL 2.0: https://www.gnu.org/licenses/old-licenses/gpl-2.0.html

from django import forms
from django.utils.translation import gettext_lazy as _

from tcms.bugs.models import Bug
from tcms.core.widgets import SimpleMDE
from tcms.management.models import Build, Version


class NewBugForm(forms.ModelForm):
    class Meta:
        model = Bug
        fields = ['summary', 'assignee', 'reporter', 'product', 'version', 'build']

    text = forms.CharField(
        widget=SimpleMDE(),
        required=False,
        initial=_("""Description of problem:


How often reproducible:


Steps to Reproduce:
1.
2.
3.

Actual results:


Expected results:


Additional info:"""))

    def populate(self, product_id=None):
        if product_id:
            self.fields['version'].queryset = Version.objects.filter(product_id=product_id)
            self.fields['build'].queryset = Build.objects.filter(product_id=product_id)
        else:
            self.fields['version'].queryset = Version.objects.all()
            self.fields['build'].queryset = Build.objects.all()


class BugCommentForm(forms.Form):
    bug = forms.ModelChoiceField(
        queryset=Bug.objects.all(),
    )

    text = forms.CharField(
        widget=SimpleMDE(),
        required=False,
    )

    def populate(self, bug_id):
        self.fields['bug'].queryset = Bug.objects.filter(pk=bug_id)

tcms/templates/plan/cases_rows.html
{% load static %}
{% load i18n %}

{% comment %}
Template for rendering rows of TestCases. Rows are TR tags used in a TABLE
tag.

Arguments:
- test_cases: an iterable object containing all TestCases. Particularly,
test_cases should be a queryset of a list of TestCases.
- selected_case_ids: used to select loaded cases.
- test_plan: its pk is used here.
{% endcomment %}
{% for test_case in test_cases %}
<tr class="case_title {% cycle 'odd' 'even' %}" id='{{ test_case.pk }}' >
	<td class="expandable js-just-loaded">
		<img class="expand blind_icon" src="{% static 'images/t1.gif' %}" border="0" alt="">
	</td>
	<td>
		{# FIXME: replacing selected_case_ids with selected_cases_ids is proper  #}
		<input type="checkbox" name="case" value="{{ test_case.pk }}"
		class="checkbox case_selector" {% if not selected_case_ids or test_case.pk in selected_case_ids %}checked{% endif %} />
	</td>
	<td>
		<a href="{% url "testcases-get" test_case.pk %}">{{ test_case.pk }}</a>
	</td>
	<td>
		<a href="{% url "testcases-get" test_case.pk %}">{{ test_case.summary }}</a>
	</td>
	<td class="col_author_content"><a href="{% url "tcms-profile" test_case.author.username %}">{{ test_case.author }}</a></td>
	<td class="col_author_content">
		{% if test_case.case_status.name == 'CONFIRMED' %} {# Show default tester when confirmed. #}
			{% if test_case.default_tester_id %}<a href="{% url "tcms-profile" test_case.default_tester.username %}">{% endif %}{{ test_case.default_tester }}{% if test_case.default_tester_id %}</a>{% endif %}
		{% else %} {# Show reviewer when not confirmed. #}
			{% if test_case.reviewer_id %}<a href="{% url "tcms-profile" test_case.reviewer.username %}">{% endif %}{{ test_case.reviewer }}{% if test_case.reviewer_id %}</a>{% endif %}</td>
		{% endif %}
	</td>
	<td class="col_tester_content expandable">{{ test_case.is_automated }}</td>

	<td status='{{ test_case.case_status }}'>
		{% if perms.testcases.change_testcase %}
		<select class="change_status_selector js-just-loaded">
			{% for case_stat in case_status %}
			<option {% if case_stat.pk == test_case.case_status_id %} selected="1" {% endif %} value="{{ case_stat.id }}">{{ case_stat.name }}</option>
			{% endfor %}
		</select>
		{% else %}
		{{ test_case.case_status }}
		{% endif %}
	</td>
	<td class="col_priority_category expandable">{{ test_case.category }}</td>
	<td class="col_priority_content expandable" align="center">{{ test_case.priority }}</td>
	<td valign="top" width="8%" class="col_category_content expandable" style="display:none">{{ test_case.category }}</td>
	<td class="col_sortkey_content" align="center">
		{{ test_case.cal_sortkey }}
	</td>
	<td align="center" >
		{% if perms.testcases.change_testcase %}
		<a class="editlink" href="{% url "testcases-edit" test_case.pk %}">Edit</a>
		{% else %}
		<span class="editlink grey">{% trans "Edit" %}</span>
		{% endif %}
	</td>
</tr>
<tr class="case_content hide" style="display: none;">
	<td colspan="12">
		<div id="id_loading_{{ test_case.pk }}" class="ajax_loading normal_cases"></div>
	</td>
</tr>
{% empty %}
<tr>
	<td colspan="12">
		<center class="prompt-message prompt">{% trans "No test case was found in this plan." %}</center></span>
	</td>
</tr>
{% endfor %}

tcms/templates/plan/get.html
{% extends "tcms_base.html" %}
{% load i18n %}
{% load static %}
{% load extra_filters %}
{% load attachments_tags %}
{% block subtitle %}{{ object.name }}{% endblock %}

{% block custom_stylesheet %}
<link rel="stylesheet" type="text/css" href="{% static 'style/print.css' %}" media="print">
<link rel="stylesheet" type="text/css" href="{% static 'style/patternfly_override.css' %}">
{% endblock %}
{% block custom_javascript %}
<script type="text/javascript" src="{% static 'js/lib/tablednd.js' %}"></script>
<script type="text/javascript" src="{% static 'js/testplan_actions.js' %}"></script>
<script type="text/javascript" src="{% static 'js/testcase_actions.js' %}"></script>
<script type="text/javascript">
Nitrate.Utils.after_page_load(Nitrate.TestPlans.Details.on_load);

Nitrate.TestPlans.Instance = {
	pk: {{ object.pk }},
	fields: {
		name: '{{ object.name }}',
		product_id: {{ object.product_id }},
		author_id: {{ object.author_id }},
		parent: {{ object.parent.pk|default:'null' }}
	},
}
</script>

<!-- temporary workaround so we can convert TestPlans.TreeView.filter to JSON RPC -->
<script src="{% static 'jquery/dist/jquery.min.js' %}"></script>
<script src="{% static 'js/jsonrpc.js' %}"></script>
{% endblock %}

{% block contents %}
<div id="content">
	<input id="id_plan_id" type="hidden" name="plan_id" value="{{ object.pk }}">
	<div class="control">
		<span id="id_buttons" class="button">
			<input id="btn_edit" type="button" value="{% trans "Edit Plan" %}" title="{% trans "Edit test plan" %}" data-param="{% url 'plan-edit' object.pk %}" {% if perms.testplans.change_testplan %}{% else%}disabled{% endif %}>
			<input id="btn_clone" type="button" value="{% trans "Clone Plan" %}" title="{% trans "Clone this plan to other product" %}" data-params='["{% url "plans-clone" %}", {{ object.pk }}]' {% if perms.testplans.add_testplan %}{% else %}disabled{% endif %}>
			<input id="btn_print" type="button" value="{% trans "Print Plan" %}" title="{% trans "Print Plan" %}" data-params='["{% url "plans-printable" %}", {{ object.pk }}]'>
			<input id="btn_delete" type="button" value="{% trans "Delete Plan" %}" title="{% trans "Delete test plan" %}" data-param="{% url 'admin:testplans_testplan_delete' object.pk %}" {% if perms.testplans.delete_testplan %}{% else %}disabled{% endif %}>
		</span>
	</div>
	<h2 id="display_title" class="{% if object.is_active == 0 %}line-through{% endif %}">
		{{ object.name }}
	</h2>
	<div class="listinfo_content">
		<div class="leftlistinfo">
			<div class="listinfo">
				<div class="title grey">{% trans "Author" %}&nbsp;:</div>
				<div id="display_author"  class="name " > <a href="{% url "tcms-profile" object.author.username %}">{{ object.author.username }}</a></div>
			</div>
			<div class="listinfo">
				<div class="title grey">{% trans "Product" %}&nbsp;:</div>
				<div id="display_product"  class="name "><a href="{% url "plans-search" %}?product={{ object.product_id }}" title="Search plans of {{ object.product }} ">{{ object.product }}</a></div>
			</div>
			<div class="listinfo">
				<div class="title grey">{% trans "Version" %}&nbsp;:</div>
				<div id="display_product_version"  class="name ">{{ object.product_version.value }}</div>
			</div>
			<div class="listinfo">
				<div class="title grey">{% trans "Plan Type" %}&nbsp;:</div>
				<div id="display_type"  class="name ">{{ object.type.name }}</div>
			</div>
		 </div>
		<div class="rightlistinfo">
			<div class="listinfo">
				<div class="title grey">{% trans "Reference Link" %}&nbsp;:</div>
				<div class="name">
					{% if object.extra_link %}
					<a href="{{ object.extra_link }}">{{ object.extra_link }}</a>
					{% else %}
					{% trans "None" %}
					{% endif %}
				</div>
			</div>
			<div class="listinfo">
				<div class="title grey">{% trans "Create Time" %}&nbsp;:</div>
				<div class="name ">{{object.create_date}}</div>
				
			</div>
			<div class="listinfo">
				<div class="title grey">{% trans "Parent" %}&nbsp;:</div>
				<div class="name ">
				{% if object.parent.pk %}
					<a href="{% url 'test_plan_url_short' object.parent.pk %}">{{ object.parent.pk }}</a>
				{% else %}
					{% trans "None" %}
				{% endif %}
				</div>
			</div>
			<div class="listinfo">
				<div class="title"><a href="/admin/testplans/testplan/{{ object.pk }}/history/">{% trans "View Edit History" %}</a></div>
			</div>
		</div>
		<div class="clear"></div>
	</div>
	<div id="plan_detail">
		<div class="Detailform border-1">
			<ul id="contentTab" class="content_tab">
				<li id="tab_document" class="tab">
					<a href="#document" title="document">{% trans "Document" %}</a>
				</li>
				<li id="tab_testcases" class="tab tab_focus">
					<a href="#testcases" title="testcases">{% trans "Cases" %} (<span id='run_case_count' class="js-testcases-count">{{ run_case_count }}</span>/<span id='case_count'>{{ object.case.count }}</span>)</a>
				</li>
				<li id="tab_reviewcases" class="tab">
					<a href="#reviewcases" title="reviewcases">{% trans "Reviewing Cases" %} (<span id='review_case_count' class="js-reviewcases-count">{{ review_case_count }}</span>)</a>
				</li>
				<li id="tab_testruns"  class="tab">
					<a href="#testruns" title="testruns">{% trans "Runs" %} (<span id='run_count'>{{ object.run.count }}</span>)</a>
				</li>
				<li id="tab_attachment" class="tab">
					<a href="#attachment" title="attachment">{% trans "Attachments" %} (<span id='attachment_count'>{% attachments_count object %}</span>)</a>
				</li>
				<li id="tab_tag" class="tab">
					<a href="#tag" title="tag">{% trans "Tags" %} (<span id='tag_count'>{{ object.tag.count }}</span>)</a>
				</li>
				<li id="tab_treeview" class="tab">
					<a href="#treeview" title="treeview">{% trans "Tree View" %}</a>
				</li>
			</ul>
			<div id="document" class="tab_list" style="display:none">
                            <div class="listinfo_doc_content">
                                <div id="display_summary" class="listinfo_doc markdown-text">
                                {% if object.text %}
                                    {{ object.text|markdown2html }}
                                {% else %}
                                    <span style="color: #666">{% trans "The document for this plan hasn't been written yet." %}</span>
                                {% endif %}
                                </div>
                            </div>
			</div>
			<div id="attachment" class="tab_list" style="display:none">
				{% include "plan/get_attachments.html" %}
			</div>
			<div id="testruns" class="tab_list" style="display:none;">
                            <!--
                                todo:
                                a temporary solution until we can convert the entire page to Patternfly
                                and figure out a way to re-use the search forms!
                             -->
                            <iframe src="{% url 'testruns-search' %}?nonav=1&plan={{ object.pk }}"
                                    width="100%" height="1000px" scrolling="auto" frameBorder="0">
                            </iframe>
			</div>
			<div id="treeview" class="tab_list" style="display:none;">
				{% include "plan/get_treeview.html" with test_plan=object %}
			</div>
			<div id="reviewcases" class="tab_list" style="display:none">
				<div class="ajax_loading"></div>
			</div>
			<div id="testcases" class="tab_list">
				<div class="ajax_loading"></div>
			</div>
			<div id="tag" class="tab_list" style="display:none">
				<div class="ajax_loading"></div>
			</div>
		</div>
	</div>
</div>
{% endblock %}

tcms/templates/plan/get_treeview.html
{% load i18n %}
<div class="mixbar">
	<div class="marginLeft fixed">
            <input id="js-add-child-node" class="add_node icon_plan left_float" type="button" value="{% trans "Add child node to current plan" %} {{ test_plan.pk }}" />
		<input id="js-remove-child-node" class="remove_node icon_plan left_float" {% if not test_plan.child_set.exists %}disabled{% endif %} type="button" 
                    value="{% trans "Remove child node from current plan" %} {{ test_plan.pk }}" />
	</div>
</div>
<div id="id_tree_container" data-param="{{ test_plan.pk }}">
	<div class="ajax_loading"></div>
</div>